language: php

sudo: false

php:
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  include:
      - php: 7.0
        env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate

install:
  - composer update --no-interaction $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
